using GameCore;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;

namespace MonogameAutoGeneratedContent{
    public static class SpriteSheet_touch_inputs
    {
        private static Texture2D Texture;
        
        public static SimpleAnimation Load_button(ContentManager content, int X = 0, int Y = 0)
        {
            //if (Texture == null)
               //Texture = content.Load<Texture2D>("touch_inputs");
            var animation = new SimpleAnimation(
                
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,68,68, new Rectangle(0, 0, 68, 68)))
            );

            return animation;
        }

        public static SimpleAnimation Load_button_pressed(ContentManager content, int X = 0, int Y = 0)
        {
            //if (Texture == null)
               //Texture = content.Load<Texture2D>("touch_inputs");
            var animation = new SimpleAnimation(
                
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,64,62, new Rectangle(0, 68, 64, 62)))
            );

            return animation;
        }

    }
}