using GameCore;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;

namespace MonogameAutoGeneratedContent{
    public static class SpriteSheet_touch_inputs
    {
        private static Texture2D Texture;
        
        public static SimpleAnimation Load_Down(ContentManager content, int X = 0, int Y = 0)
        {
            //if (Texture == null)
               //Texture = content.Load<Texture2D>("touch_inputs");
            var animation = new SimpleAnimation(
                
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,43,28, new Rectangle(0, 0, 43, 28))),
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,43,28, new Rectangle(0, 28, 43, 28)))
            );

            return animation;
        }

        public static SimpleAnimation Load_Left(ContentManager content, int X = 0, int Y = 0)
        {
            //if (Texture == null)
               //Texture = content.Load<Texture2D>("touch_inputs");
            var animation = new SimpleAnimation(
                
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,26,50, new Rectangle(0, 56, 26, 50))),
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,26,50, new Rectangle(26, 56, 26, 50)))
            );

            return animation;
        }

        public static SimpleAnimation Load_Right(ContentManager content, int X = 0, int Y = 0)
        {
            //if (Texture == null)
               //Texture = content.Load<Texture2D>("touch_inputs");
            var animation = new SimpleAnimation(
                
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,29,50, new Rectangle(0, 106, 29, 50))),
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,29,50, new Rectangle(29, 106, 29, 50)))
            );

            return animation;
        }

        public static SimpleAnimation Load_Up(ContentManager content, int X = 0, int Y = 0)
        {
            //if (Texture == null)
               //Texture = content.Load<Texture2D>("touch_inputs");
            var animation = new SimpleAnimation(
                
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,47,32, new Rectangle(0, 156, 47, 32))),
                new AnimationFrame(10, new GameCore.Texture("touch_inputs",0,0,47,32, new Rectangle(0, 188, 47, 32)))
            );

            return animation;
        }

    }
}